name: flutter_training
description: Flutter training project
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bloc: ^8.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_flavor: ^3.0.3
  flutter_localizations:
    sdk: flutter
  http: ^0.13.4
  intl: ^0.17.0 # for localization
  json_annotation: ^4.4.0
  json_serializable: ^6.1.4

dev_dependencies:
  bloc_test: ^9.0.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  build_runner: ^2.1.7

flutter:
  uses-material-design: true
  generate: true
